### ISSUE TITLE
Arrow damage not working on 1.21

### ISSUE THREAD

**Issue by FatMolePanda** [Wurst-Imperium/Wurst7#1010]
### Pre-reporting checklist

- [ ] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

The arrow damage mod is not working on the latest version of minecraft

### Repro steps

try to use arrow damage on 1.21 and it wont work but on 1.20.6 is still works

### Wurst Client version

7.43

### Minecraft version

1.21

**Comment by Alexander01998** [comment]
Hey @FatMolePanda,

Thanks for the report! I can confirm your findings.

Unfortunately the old method of increasing arrow damage no longer seems to work at all in Minecraft 1.21, possibly because of the fix for [MC-137719](https://bugs.mojang.com/browse/MC-137719) that's included in this update.

I will update ArrowDMG to use a different method of increasing arrow damage in Minecraft 1.21+. Unfortunately that new method is less powerful than the old one, so we won't be able to one-shot wardens or iron golems anymore.
