### ISSUE TITLE
Escape crash still not fixed 

### ISSUE THREAD

**Issue by basil222** [Wurst-Imperium/Wurst7#1023]
in Wurst 7.43.1 it says Escape crash has been fixed, but after testing, its still not fixed :/

**Comment by Alexander01998** [comment]
Hey @basil222,

There are actually two different Escape crashes. Wurst 7.43.1 fixes the vanilla Escape crash, caused by Minecraft 1.21’s new server links feature. However, the crash you seem to be experiencing is the ModMenu Escape crash, caused by ModMenu's v11.0.0 update, which was released one day after Wurst 7.43.1.

There are currently four different ways how you can prevent the ModMenu Escape crash:
- Stop using ModMenu.
- Downgrade ModMenu to [v11.0.0-rc.4](https://modrinth.com/mod/modmenu/version/11.0.0-rc.4).
- Change ModMenu's "Game menu: Replace" setting to either "Game menu: Insert" or "Game menu: Icon".
- Update Wurst to [v7.44pre1](https://www.wurstclient.net/updates/wurst-7-44pre1/).

Any one of these changes will completely stop the crash.

Hope this helps and clears up any confusion.
