### ISSUE TITLE
Automatically Get OP

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [Wurst-Imperium/Wurst7#1039]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack., Adding a new chat command.

### What type of player would find this improvement useful?

Builders, Miners, Griefers, PVPers, Anarchy/faction players

### Description

This will allow players to become an admin of the server and they will have the ability to ban other admins, close the server (EDUCTATIONAL PURPOSES)

**Comment by Alexander01998** [comment]
I'm sorry, @GuestSneezeOSDev. I know it's rude but I couldn't resist:

![A two-panel meme depicting a man transitioning into a clown. In the left panel, the man is having white makeup applied to his face. In the right panel, he is fully made up as a clown with colorful rainbow hair, a red nose, and exaggerated facial makeup. The text below the image reads, "I have looked at the code and am reasonably confident that this suggestion is possible to implement."](https://github.com/user-attachments/assets/6ac1ea63-9f94-4891-b42b-347dfa8f02b1)

To be clear, no, this suggestion is absolutely not possible to implement. The reason for this boils down to how Minecraft servers work and where they store their data.

Generally, Minecraft servers, not clients, hold the authority over player's status, like their game mode (Creative, Survival, etc.), permission level (OP vs. not OP), and some other things. The server maintains a whitelist of approved operators and checks this list anytime an operator command is used. This list is stored securely on the server side.

What a client-side hack can do is limited by which parts of the game are controlled by the client-side and what inputs the server will accept. You can do almost anything on your local singleplayer world because your client is the server in this case, and it has full authority. But on a normal multiplayer server, the server is someone else's computer, which you don't have access to.

So unless the server specifically allows it, or a major security flaw is found in Minecraft, a client cannot just turn itself into an operator, as all of the data and logic for that is stored securely on the server side in a place that the client cannot reach. It has nothing to do with fears that such a feature might be abused for non-educational purposes. It simply isn't possible.

I hope that clears it up. Sorry again for clowning you but that really is the worst use of that checkbox I have seen in a long time.

**Comment by GuestSneezeOSDev** [comment]
Thank you anyway
