### ISSUE TITLE
Please allow hiding the logo permanently.

### ISSUE THREAD

**Issue by bobbyl140** [Wurst-Imperium/Wurst7#1066]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### What type of player would find this improvement useful?

Other (please explain in description)

### Description

I think that for user choice there needs to be an option to never show the wurst logo. I have multiple other mods that show data near the top-left corner, and having the Wurst logo there is quite intrusive because it shows up over top of that info. Not all users want to constantly stay on the latest version. Additionally, right now I am on the latest non-beta (non-paid) version of Wurst, but because of the option to pay for the beta release, the logo is there no matter what I do (aside from paying for the beta). Please consider giving users the choice here to not have the logo show at all.
Thank you.

**Comment by Alexander01998** [comment]
Hey @bobbyl140, there seems to be a huge misunderstanding here.

Paid pre-releases do not and cannot cause the logo and/or "(outdated)" message to appear. (And just to be clear, an update being available for a different Minecraft version won't trigger the logo/message either.) This system is very carefully designed to not show any false update notifications.

[Wurst 7.46](https://www.wurstclient.net/updates/wurst-7-46/) is actually out of early access and available for free now, which is likely why you're seeing that message.

As for showing the logo on outdated _Wurst versions_ (using outdated Minecraft versions is fine, like I said), this is unfortunately necessary just for practical reasons.

You would be surprised how many people will encounter an old, already fixed bug, and instead of updating they try to re-report that bug while trying to hide the fact that they're using an outdated Wurst version. These people have wasted so much time with their fake bug reports that I had to implement a system like this. Some even made YouTube videos or public posts with these old buggy versions to try and make Wurst look bad.

In a perfect world no one would do such things, but in the real world you're always going to have a few bad actors that try to ruin it for everyone. I think showing the outdated notice on old versions (which, again, will NEVER nag you to pay for a pre-release) is a lot better than disabling the downloads for old versions completely (which is what most other clients are doing).

Hope this makes sense!

**Comment by bobbyl140** [comment]
Hey, I'm sorry I misunderstood. I downloaded Wurst for 1.21.1 today about 10 minutes before making this issue, and on the website the only reference to the newer version listed was an early access build. I'll check again but I'm really sorry I didn't notice that.

**Comment by bobbyl140** [comment]
And ps. I totally understand about the bug reports for old versions thing. It makes sense to me, I guess that people wanting old versions (though that seems unlikely now) would just have to have the logo as a drawback because it prevents the bug reports.
