### ISSUE TITLE
Where is the 1.12.2 source code?

### ISSUE THREAD

**Issue by Zinibow** [Wurst-Imperium/Wurst7#191]
Where is the 1.12.2 source code?

**Comment by Alexander01998** [comment]
Because of how Wurst works, this is basically 3 questions in one. I will answer them separately:

### Question 1 - Where is the Wurst 7 source code for Minecraft 1.12.2?
Wurst 7 is only for Minecraft 1.14.x and newer versions. It doesn't exist for Minecraft 1.12.2.

### Question 2 - Where is the Wurst 6 source code for Minecraft 1.12.2?
Wurst 6 uses the Minecraft Coder Pack (MCP), which works by directly modifying the Minecraft source code. This is problematic, because Minecraft's source code is proprietary and can't legally be included in a public GitHub repository.

Until roughly August 2018, Wurst 6 included a patch file that included only Wurst's modifications to Minecraft's code, but none of the actual Minecraft source code. This system solved the problem, but it was extremely cumbersome. Contributors didn't understand it, it slowed down development and sometimes it didn't even work because the patch file could easily get corrupted.

Nowadays, the Wurst 6 repository simply includes the modified Minecraft source code. Because Minecraft's source code is proprietary, this means I can no longer publish the Wurst 6 repository. Wurst 6 still doesn't use any obfuscation, so you can always decompile releases to get the source code.

The last version of Wurst 6 MC 1.12 that used this patch system (v6.23) is still available here: https://github.com/Wurst-Imperium/Wurst-MC-1.12.

### Question 3 - Where is the ForgeWurst source code for Minecraft 1.12.2?
Right here: https://github.com/Wurst-Imperium/ForgeWurst
