### ISSUE TITLE
holeESP

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst7#230]
Just highlights holes in bedrock or obsidian showing safe places for crystal pvp. Red for an all obsidian hole, yellow for a partly bedrock hole, and green for an all bedrock hole (similar to salhack or future). Make sure that 1.12.2 gets this hack as well. (you could probably pull the code for hole esp over from salhack now that I think about it since its open source)

**Comment by Alexander01998** [comment]
Could you post a screenshot to give an idea of what this would look like? I don't do crystal PVP at all so I'm a little lost as to what these "holes" are.

**Comment by Lovecrafts-Cat** [comment]
I would like to help explaining how this hack is supposed to work, let's start by talking about End Crystal pvp: when you use them as a weapon they must be placed on either obsidian or bedrock, and usually crystal pvp happens near bedrock. To use crystals safely without dying the player must enter a 1x2 hole so that his legs are covered and make sure that there is at least one block at torso height. The player will proceed by placing a crystal on the closest block in a way that he is covered from the explosion, then detonate the crystal asap.

Knowing this we must check for some variables which will define how safe is a hiding hole, these are:
1. Which material compose the hole?
2. Which material is at the base (under the player), to ensure no one could sneak from under you?
3. Is there any valid surface to place the crystal?
4. Is the player capable of breaking the crystal from within the hole?

Let's analyze the first condition, here we have 3 possibilities: 
1. The hole is surrounded by bedrock  (best)
![2020-11-20_12 30 49](https://user-images.githubusercontent.com/52252627/99797243-2dfdd800-2b2f-11eb-947e-5b56507e9413.png)
2. The hole is surrounded by obsidian
![2020-11-20_12 32 29](https://user-images.githubusercontent.com/52252627/99797273-3eae4e00-2b2f-11eb-956e-1dba263e26f0.png)
3. The hole is surrounded by any other material (worst)
![2020-11-20_12 33 06](https://user-images.githubusercontent.com/52252627/99797295-4a017980-2b2f-11eb-9e4b-a74d98d1cbae.png)
It is important to note how the torso is always covered by a block between you and the crystal.

The second condition is not as important, but having a better floor will prevent the need of replacing it if it gets blown up and should be decisive to define the safety of the hole.
The third condition is a clear must, if there is no surface to place the crystal the previous effort is wasted.
The fourth condition is useful to setup a Legit Mode (can hit the crystal if in line of sight) and a Simple Mode (uses reach/killaura to hit the crystal right after placement).
Other pvp clients usually highlight these holes using green, yellow and red; most of them also add a filter function, so it only renders holes with a certain  tier of safety. If more photos/ extra explaination is needed do not worry and ask me.

**Comment by HappyNerd1** [comment]
yeah sorry for the late response. another visualization of this is from FitMc's video "Useless" 2b2t Hacks that are actually INSANE. here's a link. https://www.youtube.com/watch?v=xeI3x1PhV8Y you watch from 1:14 to 2:56

**Comment by Alexander01998** [comment]
I have some follow-up questions.

The FitMC video seems to suggest that HoleESP only considers 4 blocks around a given spot and ignores the diagonals.

![image](https://user-images.githubusercontent.com/10100202/99899797-624ad300-2cac-11eb-9820-8a5fb4d5819c.png)

If I remember correctly, TNT explosions can go through diagonal "gaps" like this, but I've never tried it with end crystals.

@Lovecrafts-Cat's screenshots show all eight blocks around the spot (and even one block at head height which the FitMC video seems to ignore completely).

![image](https://user-images.githubusercontent.com/52252627/99797273-3eae4e00-2b2f-11eb-956e-1dba263e26f0.png)

How important are the diagonals for crystal PVP? Can a 4-block hole as shown in the FitMC video be bypassed by placing a crystal in the corner?

Do I understand correctly that the block at head height is optional, because most of the damage is already absorbed by the blocks at foot height?

**Comment by Lovecrafts-Cat** [comment]
Did some testing right now, look at the crystal placement in this screenshot:
![2020-11-22_11 00 30](https://user-images.githubusercontent.com/52252627/99900799-29156180-2cb2-11eb-9cdb-b38b5062d721.png)
If the crystal is on a corner at leg level (green) you mitigate the damage, but at torso level (red) the explosion can hit your legs and kills you, this is why i consider the presence of a block at torso height, as it prevents the damage if you hide behind it.

This means that any crystal placed at torso level will kill you if there is no cover at the same height.

**Comment by FarmerJoe2b2t** [comment]
> This means that any crystal placed at torso level will kill you if there is no cover at the same height.

no, if you have full armor and blast protection, which you should have for crystal pvp, this will do almost no damage. 
you only need to cover the 4 blocks around the feet.

**Comment by JamesTheAwesomeDude** [comment]
Flipping this on its head, it'd also be useful for escaping spawn on anarchy servers: you know _to avoid_ the green ESP highlights

**Comment by Cyclopropinon** [comment]
> Flipping this on its head, it'd also be useful for escaping spawn on anarchy servers: you know _to avoid_ the green ESP highlights

@JamesTheAwesomeDude why would u exactly avoid them?
