### ISSUE TITLE
X-ray doesn't work properly in the nether

### ISSUE THREAD

**Issue by RENNAARENATA** [Wurst-Imperium/Wurst7#338]

**Comment by JamesTheAwesomeDude** [comment]
It works perfectly for me.

> a lot of blocks that actually doesn't exists

Sounds like the server has an anti-xray plugin

**Comment by RENNAARENATA** [comment]
> It works perfectly for me.
> 
> > a lot of blocks that actually doesn't exists
> 
> Sounds like the server has an anti-xray plugin

In the normal world it works btw...

**Comment by AndrewBruhMoment** [comment]
Send some screenshots of what you are experiencing. 

If you are on a server this may be caused by an anti-xray plugin, which replaces blocks that are not open to the air with other blocks to prevent using xray. 

If xray is working fine in a single-player world, then the server most definitely has the plugin, and xray will not work on that server.
