### ISSUE TITLE
[SUGGESTION] Auto Crystal

### ISSUE THREAD

**Issue by Drakesdrs** [Wurst-Imperium/Wurst7#374]
I seriously wonder how auto crystal has not been implemented in wurst yet, this peeks my interest greatly.
I already know there is a function to automatically break end crystals but there is no module for automatically placing and breaking end crystals.

## Description
A Module that Automatically breaks and places end crystals.
## Screenshots / Videos (Optional)

![Cpvp](https://user-images.githubusercontent.com/67423571/115747409-c15c6300-a384-11eb-9097-81db2695dc58.gif)

**Comment by Drakesdrs** [comment]
https://www.wurstclient.net/updates/wurst-7-15/

There is literally a re spawn anchor bot but no crystalaura

**Comment by Alexander01998** [comment]
Why would you need a CrystalAura when respawn anchors are so much better? From what I understand it looks like CrystalAuras are becoming obsolete, with even the 2b2t server updating to 1.16 and switching to anchors for PVP.

Is there any use for crystals in 1.16? If so, I could probably adapt the AnchorAura code to work with crystals too.

**Comment by Drakesdrs** [comment]
> 
> 
> Why would you need a CrystalAura when respawn anchors are so much better? From what I understand it looks like CrystalAuras are becoming obsolete, with even the 2b2t server updating to 1.16 and switching to anchors for PVP.
> 
> Is there any use for crystals in 1.16? If so, I could probably adapt the AnchorAura code to work with crystals too.

Some times you crystalpvp in the nether. where anchoraura cannot be used.

**Comment by Alexander01998** [comment]
> Some times you crystalpvp in the nether. where anchoraura cannot be used.

Ah yes, that makes sense.

**Comment by Drakesdrs** [comment]
> 
> 
> > Some times you crystalpvp in the nether. where anchoraura cannot be used.
> 
> Ah yes, that makes sense.

Indeed, it would be great if you could add crystalaura, crystalpvp won't just die because of anchorpvp.

**Comment by ccuser44** [comment]
Crystal aura and Auto Crystal should be seperate

**Comment by Alexander01998** [comment]
Added in fde40f5a0de09714b17911ff139f4f7b0d5a94a9.

**Comment by Drakesdrs** [comment]
@Alexander01998 what was that for

**Comment by ccuser44** [comment]
> @Alexander01998 what was that for

They added it as a feature

**Comment by Alexander01998** [comment]
Hi @Drakesdrs, two things happened here:

1. You were temporarily blocked in May of 2021 due to an inappropriate comment, which can be seen above. Please remember to communicate respectfully and constructively when giving suggestions or discussing improvements, that way we can maintain a productive and welcoming environment for everyone.

2. I closed this issue in May of 2022 as it's been resolved - I've added the CrystalAura feature in the [Wurst 7.16](https://www.wurstclient.net/updates/wurst-7-16/) update (released in August of 2021). Every version since then comes with this feature included.

I hope this clears things up for you. Let me know if you have any further questions.

**Comment by Cyclopropinon** [comment]
stilll waiting for bed-aura :meltingface:

**Comment by Alexander01998** [comment]
Hi @Cyclopropinon,

I understand wanting certain features, but it's important to keep in mind that when I add features to Wurst, I'm doing it on my own time, for free, and prioritizing those that are the most popular or that I believe will yield the highest benefit to the community.

Your BedAura request (#795) is very specific and to date, you're the only person who has asked for it. It's difficult for me to prioritize it when there are other more widely requested features and improvements that need my attention.

You're more than welcome to work on implementing BedAura if you really need it! A well-tested pull request that follows the style guide would greatly increase the chances of it being added to Wurst. And feel free to reach out if you have any questions about the codebase or run into any problems with it. Just remember that I can't be everywhere at once.

But please don't melt your face, hijack unrelated conversations, and demand that I add a feature just because you suggested it. That's not how open-source projects work.

Thanks for your understanding.
