### ISSUE TITLE
Support for localization (translation)?

### ISSUE THREAD

**Issue by SiongSng** [Wurst-Imperium/Wurst7#404]
## Description
Will Wurst support localization?
I would like to translate Wurst through the lang file so that other users can translate Wurst into their language as well.

**Comment by SiongSng** [comment]
I got it, thank you.

**Comment by SiongSng** [comment]
Sorry for the interruption, is there an estimated time of arrival (ETA) from the i18n branch to the master branch?

**Comment by Alexander01998** [comment]
I plan to merge the i18n branch into master once it's ready to be included in a Wurst update.
With the current amount of translations I think it's still too early to release this feature.

**Comment by SiongSng** [comment]
Ok thanks for your reply

**Comment by Alexander01998** [comment]
I am seeing more and more cases where translators are disagreeing about how something should be translated. Of course, I can't resolve these conflicts by simply checking with Google Translate and trying to guess which translation is better, in a language that I don't even speak.

I think we might need some kind of community voting system, so that people who natively speak these languages can vote on each individual translation, rather than me trying to choose between entire pull requests that contain up to 137 translations each.

**Comment by SiongSng** [comment]
You can use a platform like Crowdin, which has a community voting feature

**Comment by MineYuanlu** [comment]
I suggest that in the search function, you can search the translated language and original English at the same time.

**Comment by KTibow** [comment]
Implemented. Consider closing?

**Comment by b1ek** [comment]
I can help with the Russian translation

**Comment by Alexander01998** [comment]
@b1ek We already have Russian translations of all hack descriptions. Only a few tooltips in AltManager are currently missing Russian translations.

Please talk to @faseri if you think the current Russian translations should be improved. Please do NOT simply open another Pull Request with different translations, as I don't natively speak Russian and thus have no way of knowing which translation is better.

**Comment by b1ek** [comment]
@Alexander01998 sorry, i didn't know that. You should add a list with translated languages somewhere so this won't happen again.

**Comment by Alexander01998** [comment]
@b1ek I agree. I've added [a table](https://github.com/Wurst-Imperium/Wurst7/blob/master/README.md#current-status-of-translations) to the README file.

**Comment by skidderrom** [comment]
Hi, Alex!
I sent this on Twitter, but since you seem are not that active on it, let me post it here too!

I and a friend of mine found that you're looking for the translators yesterday, and checked the current translations on Github, but it seems all the strings in Japanese translation are "translated" by using Google translate (and as you may not know, Google translate sucks, especially on Japanese).
So we're currently re-translating every single string ourselves.
Could you replace the file when the translating is done please? Not sure when exactly, but we've already translated all the strings and all we need to do is only proofreading, so it'd be done soon!

**Comment by Alexander01998** [comment]
@skidderrom Great! I have been looking for a Japanese proofreader for some time.

I actually [asked on Twitter](https://twitter.com/Wurst_Imperium/status/1468596985229979661) if anyone could proofread that translation before I merge it, but at the time nobody replied. Eventually I just merged it, hoping that someone would eventually notice if anything is wrong with it. Seems like that's exactly what happened now. :)

BTW, Twitter doesn't notify me about DMs for some reason. I only saw your message now. A tweet usually works better.

**Comment by skidderrom** [comment]
@Alexander01998 Thank you for the reply!
I'm sorry if I'm dumb, but how should I upload the file when the translating is done?
I suppose what I'm supposed to do is to folk the repo, update the ja_jp file, and make a pull request, but am I wrong?

**Comment by Alexander01998** [comment]
> I'm supposed to fork the repo, update the ja_jp file, and make a pull request, right?

Yes.

You can actually do this all in the browser by clicking the pen icon [here](https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/resources/assets/wurst/lang/ja_jp.json).
[![image](https://user-images.githubusercontent.com/10100202/159102396-f8c3c6fe-0f49-44e7-8922-f963adf05858.png)](https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/resources/assets/wurst/lang/ja_jp.json)

Or, if you set it up locally with Eclipse and all that, it will let you preview the translations in-game before submitting.

**Comment by skidderrom** [comment]
@Alexander01998 Thank you for the help! <3
Just made a pull request. ;)

**Comment by Alexander01998** [comment]
I've replaced the big translations table in the readme file with GitHub's new "Projects Beta" feature. It's kind of like Notion, but built into GitHub.

The overview of how many strings have been translated to each language is now here: https://github.com/orgs/Wurst-Imperium/projects/4/views/1

And an overview of all pending translations and their status is now here: https://github.com/orgs/Wurst-Imperium/projects/4/views/3
