### ISSUE TITLE
Barrels not highlighted with chestESP

### ISSUE THREAD

**Issue by TheWienerMaster** [Wurst-Imperium/Wurst7#439]
![image](https://user-images.githubusercontent.com/61437644/124338119-d4728700-dbae-11eb-9258-cfb806a97bb3.png)

**Comment by holysnipz** [comment]
me too, with Wurst 7.15.3 *(both public release and self-compile)* on Fabric Loader 0.11.6, Fabric API 0.36.0

![image](https://user-images.githubusercontent.com/9103583/124351002-12f55980-dc22-11eb-9813-25d5fc06e450.png)

I've add a quick print to log, and found that Barrel is no longer found in EntityTicker somehow
https://github.com/Wurst-Imperium/Wurst7/blob/0be62903df6a9f4ed564801e179c99714e257313/src/main/java/net/wurstclient/hacks/ChestEspHack.java#L119-L120

<details>
<summary>part of log (since it keep repeating)</summary>

```
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:mob_spawner
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:mob_spawner
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:mob_spawner
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:mob_spawner
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:mob_spawner
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:mob_spawner
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:ender_chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:trapped_chest
[Render thread/INFO]: [CHAT] §c[§6Wurst§c]§r minecraft:shulker_box
```

</details>

**Comment by GooUckd** [comment]
This could be fixed by adding a feature to add blocks into ChestESP, or just adding a feature to swap X-Ray's blocks via keybinds to see barrels for example.

**Comment by RedCat888** [comment]
I also have this issue with like almost all versions of 1.17 Wurst
