### ISSUE TITLE
Error on compile : Wurst-Client-refmap.json is missing

### ISSUE THREAD

**Issue by SecretUser001** [Wurst-Imperium/Wurst7#49]
When I am trying to build the Client (gradlew build) i get the following error log :

gradlew build

> Configure project :
Fabric Loom: 0.2.6-SNAPSHOT Build(jenkins #31)
:setting up loom dependencies
:setting up mappings (yarn 1.15.2+build.7)

> Task :compileJava
:setting java compiler args
Could not find refmap definition, will be using default name: Wurst-Client-refmap.json
error: cannot access Immutable
  class file for javax.annotation.concurrent.Immutable not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
1 actionable task: 1 executed

I thing It means the file Wurst-Client-refmap.json is missing.
(In older versions that file is included)

**Comment by Alexander01998** [comment]
1. You cannot run `build` without running `genSources` and `eclipse` first.
2. Make sure that you have a working JDK installed (preferably Java 8).

---

> Could not find refmap definition, will be using default name: Wurst-Client-refmap.json

That's not an error. It's just saying that Gradle will generate a refmap instead of using a pre-made one. This is supposed to happen.

To get the actual error, as Gradle is saying, you must run the command with `--stacktrace`,  `--info`, `--debug` or `--scan`.

> I thing It means the file Wurst-Client-refmap.json is missing.
> (In older versions that file is included)

Where is it then? I know I have never created that file. Every Wurst 7 (pre-)release so far has been compiled with that warning.
