### ISSUE TITLE
x-ray does not render y -6 to -60

### ISSUE THREAD

**Issue by typho0nz** [Wurst-Imperium/Wurst7#507]
## Description

x-ray does not render below y -6
since mc version 1.17 (and now 1.18) it should render until y -60

there seems to be an oversight with the update. most stuff works fine, this sadly not.
let me know if you need more infos.

best regards.

**Comment by Alexander01998** [comment]
Works fine for me.

![2021-12-02_07 14 47](https://user-images.githubusercontent.com/10100202/144368189-b9a3c388-66db-4f2c-8f98-eb32ce2c9f4f.png)

It sounds like you are still using a pre-1.17 ore list (without the deepslate ores). X-Ray includes these ores by default ever since the Minecraft 1.17 snapshots added them.

Try resetting your X-Ray Ores setting to the defaults.

**Comment by typho0nz** [comment]
You are absolutely right. Resetted the ore-list to default and now everything shows fine!

Strange thing is that this was a fresh mc install with 1.17 and later the 1.18 pre's and first time that I used wurst in years - so I rly dont know how a pre-1.17 list was there in the first place.

Anyway - thank you so much!
