### ISSUE TITLE
Chat bot for chat iteractions

### ISSUE THREAD

**Issue by LocalSmail** [Wurst-Imperium/Wurst7#584]
### **Add a bot to send a message when it says to say xyz or unscramble xyz**

Unscramble could take a user input in its settings to save the scrambled word and unscramble (so basically a table) which when that work comes up it would automatically say the word the user set for it within the table.

The say xyz could just take user input for each word inside a separate table and could then just say it when it comes up, like the unscramble (but not as much of a pain I would guess)

Heres an example of the say xyz
![request](https://user-images.githubusercontent.com/96918131/154844953-90ea5a1b-90a6-430c-9b17-9707fe900cc9.PNG)

**Comment by Glutius** [comment]
I actually made this a few days ago, and been using it since with no problems. I attached some screenshots.
![javaw_bgDkRFUnsv](https://user-images.githubusercontent.com/12672076/155221979-583be4a1-c19a-4ddb-8af5-37a7882de635.png)
![javaw_zBYRNr1Lx3](https://user-images.githubusercontent.com/12672076/155221976-ab0574ad-7c07-424f-b4e7-36575e15d3cc.png)

Should I submit this?

**Comment by cakarlen** [comment]
Submit it!

**Comment by LocalSmail** [comment]
submit that shit looks well made!

**Comment by cakarlen** [comment]
@Glutius You still have this code?

**Comment by Glutius** [comment]
I still have the code but didn't publish it since I wanted to make a separate file for the hack to read the questions and answers from, but didn't want to add any more stuff I didn't have to and just left it as is. I can publish the code as is which is usable, and if someone wants to help can do it :)

**Comment by cakarlen** [comment]
I'd be more than happy to contribute to it if you'd like to fork and commit it. I can make adjustments from there. Thanks!

**Comment by Glutius** [comment]
https://github.com/Glutius/Wurst7/tree/autoreply
Here it is, feel free to contribute to making it read some lines from a config file, and then we can make a pull request :)

**Comment by Glutius** [comment]
I forgot to mention that the code was for 1.18.2, so some adjustments might be needed. And sorry for the sloppy code. This was one of the first java stuff I've worked on.
Basically, we need a config file with phrases of the start, won, and end messages of the questions games, along with the questions. And the hard-coded questions would just be replaced with a for loop.
@Alexander01998, keep up the awesome work!

**Comment by Alexander01998** [comment]
@Glutius Thanks! By the way, is that WitchChat server public? Would be useful for testing if I could join it.

**Comment by Glutius** [comment]
Server is public, but they now changed their plugin, using something that has questions & random math. Lookup sentouki
