### ISSUE TITLE
Microsoft Account login STILL fails to login

### ISSUE THREAD

**Issue by Aripander088e2** [Wurst-Imperium/Wurst7#758]
I know it says that wurst 7.31 fixes this but it didn't. Originally i could get it to login by spamming the login button but that doesn't even work anymore

**Comment by Alexander01998** [comment]
I just tried it on my end and it logged me in on the first try. It's been working fine for me ever since the v7.31 update (with no need to spam the login button anymore), so I'm not sure what could be causing the issue on your end.

Are you sure you're using Wurst 7.31? It's possible that you might be on an older version that still has the login issue.

**Comment by Aripander088e2** [comment]
(both of our names are Alexander, but I prefer Alex over Alexander lol)

I was using wurst 7.31 I believe.

I don't know if it is because I have a bad computer or if my account is in the security code wait period. That's all I have to say
________________________________

**Comment by Aripander088e2** [comment]
It works now, Also, is there any way that I can get beta jars to test for you?
________________________________
