### ISSUE TITLE
Wurst 1.17: Incompatible modset!

### ISSUE THREAD

**Issue by imlens** [Wurst-Imperium/Wurst7#774]
## Description
Hello! I'm using Wurst Client for 1.17 and I followed the tutorial [here](https://www.wurstclient.net/tutorials/how-to-install/wurst-7/). Everything seems normal and the fabric loader appears in the Minecraft launcher. After I launch, Fabric loader opens with an error that is in the crash report section

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install Wurst 1.17 from the official website
2. Install the fabric api
3. Put both the fabric api and Wurst in the .minecraft/mods folder
4. Run fabric loader and install it for 1.17
5. Launch in Minecraft client

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.
No crash reports.
```

(crash report goes here)
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.17 with any version between 1.17.1-rc2 (inclusive) and 1.18- (exclusive).
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.46.1+1.17 requires any version between 1.17.1-rc (inclusive) and 1.18- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17!
	 - Mod 'Wurst Client' (wurst) v7.15.3-MC1.17.1 requires version 1.17.1-rc2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.17!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
The above is from fabric.

For further please visit this Github discussion in the fabric repository.
https://github.com/FabricMC/fabric/discussions/2890

**Comment by Alexander01998** [comment]
Hello 1enss,

This error is caused by selecting 1.17 in the Fabric installer, but using the 1.17.1 versions of all of your mods (Wurst and Fabric API).

To fix this, either select 1.17.1 in the Fabric installer or replace all of your 1.17.1 mods with the 1.17 versions, depending on which Minecraft version you want to use.

As for the tutorial that you followed, I would like to point out that it actually explains the error you are getting in this section: https://www.wurstclient.net/tutorials/how-to-install/wurst-7/#error-replace-minecraft-x-with-version-y

I hope this helps. If you have any more questions, feel free to reach out to me.
-Alexander01998

**Comment by 1enss** [comment]
Ok. Thanks for you're help. I'll try it. By the way, do you think that the .dupe feature of 1.17 Wurst would work in a server called herobrine.org?

**Comment by niebieskaowca123** [comment]
so i had same im on 1.19.4 can someone help pls
