### ISSUE TITLE
Portal ESP

### ISSUE THREAD

**Issue by Cyclopropinon** [Wurst-Imperium/Wurst7#776]
Before posting, please make sure that this hasn't already been suggested by someone else. yep i did

## Description
similar to chest ESP, but highlights netherportal-blocks, endportal-blocks and endgateway-blocks etc. probably each toggleable in the settings.
This can be added in literally any minecraft version since minecraft alpha or so lol (idk what the oldest minecraft version is that supports wurst)

## Screenshots / Videos (Optional)
couldnt find any sorry

**Comment by DrMaxNix** [comment]
I'd also like to have a PortalESP feature.. I did some tests and here is something you could call a proof of concept:

![Screenshot_2023-04-27_17-44-43](https://user-images.githubusercontent.com/38893656/234915881-2dd5e762-1a3f-43ad-9cb0-b4ef173b2565.png)
![Screenshot_2023-04-27_17-52-27](https://user-images.githubusercontent.com/38893656/234917559-f0bbe321-08e2-4381-a418-903ae30031f5.png)

**Comment by Cyclopropinon** [comment]
nice!
maybe u can add tracers
(and the color changeable)

**Comment by DrMaxNix** [comment]
Yup, making the color changeable will be no problem (setting different colors for different portals is hard tho)
Tracers will also be quite a challenge because I stole the code from the `Search` hack which has no colors :/
All of this rendering stuff is rather new to me so it may take me some time to figure things out.. But I'm looking forward to make this a fully-fledged feature! :)

**Comment by Cyclopropinon** [comment]
what about stealing code from chestesp?
there u can toggle each of them
and change color seperately 
etc

**Comment by Cyclopropinon** [comment]
btw why stealing. just borrow it. and return the code afterwards :trollface:

**Comment by DrMaxNix** [comment]
Yup, that's what I tried initially, but all the Blocks tracked by ChestESP are BlockEntities, which can be easily obtained as a list from the respective chunk. While that works with End Portals and End Gateways, it doesn't seem to work with Nether portals, which are just regular Blocks and need to be searched manually.

**Comment by Cyclopropinon** [comment]
hm ok
but good job till here
(btw it just came in my mind, what about also adding end portal frames, so an unfinished portal can be found too?)

**Comment by DrMaxNix** [comment]
> btw it just came in my mind, what about also adding end portal frames, so an unfinished portal can be found too?
That would be no problem, just add another option to the hack to enable/disable searching for end portal frames :)
(The hardest parts is the block searching and the rendering, everything else is just adding a few lines)

**Comment by Cyclopropinon** [comment]
@DrMaxNix how have you been doing about that?
is it finished?

**Comment by DrMaxNix** [comment]
Sadly I wasn't able to work on this the last weeks due to other projects that were more important and me not having a lot of time to spare in general (life is a thing). There is still a lot to do for the PortalESP hack to be ready for release. I hope I will find time to continue development sometime the next weeks.
@Cyclopropinon If you want we can develop it together.. Feel free to write me an email to the mail address displayed on my github profile :)

**Comment by DrMaxNix** [comment]
All features have been implemented, after some polishing and testing the hack will be ready for a PR!
![Screenshot from 2023-06-08 15-10-46](https://github.com/Wurst-Imperium/Wurst7/assets/38893656/12c39624-b436-4f3c-be0c-ef3749940b07)
![Screenshot from 2023-06-08 15-11-49](https://github.com/Wurst-Imperium/Wurst7/assets/38893656/87e9f535-3f5f-4b17-8ca6-0ef8c38bed7b)
![Screenshot from 2023-06-08 15-11-54](https://github.com/Wurst-Imperium/Wurst7/assets/38893656/c273b664-f4a2-4037-8e1b-e1a54f8825b3)

**Comment by Alexander01998** [comment]
The pull request is still in progress. PortalESP works, but has performance issues that I would like to fix before merging.
