### ISSUE TITLE
Can't run minecraft after building.

### ISSUE THREAD

**Issue by utf69** [Wurst-Imperium/Wurst7#8]
I've tried building with Gradle (.\gradlew.bat jar), but minecraft always crashes when I try to run it with my version of Wurst (I didn't change a single line at all).

There were some Mixin errors before the crash:
https://pastebin.com/1v7frELP

Crash report:
[crash-2019-09-21_19.55.12-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/3638946/crash-2019-09-21_19.55.12-client.txt)

**Comment by THEREALWWEFAN231** [comment]
One would assume you are in a development environment because that shouldn't happen when compiled, but i dont know how you could import the project without running theses commands(they are even shown on this repository's main page)
./gradlew.bat genSources
./gradlew.bat eclipse
once you do that, and import the project as an existing project into eclipse it will run
all you really have to do if your on windows is gradlew genSources eclipse

**Comment by Alexander01998** [comment]
> I've tried building with Gradle (.\gradlew.bat jar)

That's the wrong command. The command to build is: `./gradlew.bat build`

That, and you need to run the setup before building will work:
```
./gradlew.bat genSources
./gradlew.bat eclipse
```
(The second line is optional if you just want to build the project without using Eclipse.)
