### ISSUE TITLE
in minecraft 1.20.1, I used wrust, in game , I can't send messages,the game tell me that my public lost, them I disabled wrust, it become ok

### ISSUE THREAD

**Issue by Ezgx** [Wurst-Imperium/Wurst7#856]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. 
2. 
3. 

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by RealmKebab** [comment]
please elaborate

**Comment by impresson** [comment]
Oh ok I know what happens. And I know why. It's because the server you're playing on has `secure profile something something something` that was implemented by mc devs for chat reporting.  Wurst devs made a fix to that and implemented a NoChatReport.  In the latest update it became a module so you dont have to worry about it. But if you dont want to update you and if you own the server. You can turn of secure chat profileing smth.
