### ISSUE TITLE
New hack suggestion: PlayerPanic

### ISSUE THREAD

**Issue by Qwikster** [Wurst-Imperium/Wurst7#888]
PlayerPanic: Immediately turn off all hacks when a player comes within a certain radius of you (with a few thoughts ie. keep NoFall on if Flight or Jetpack is enabled). This would be useful for discreetly hacking on a multiplayer server.

**Comment by impresson** [comment]
That's Accually pretty cool

**Comment by Chris6ix** [comment]
If this gets some customizability so that you can whitelist certain hacks so that they don't get disabled, then yeah, this sounds cool.
What is an absolute must for this IMO is a player whitelist, where you can then whitelist your friends for example, so that it doesn't turn off your hacks because your friend got close to you (Who is probably also hacking).

**Comment by finallyout** [comment]
I started working on this today. So far I have some (untested) code for this feature which I'm calling "autopanic":
1. Turn off all hacks when another player is within some adjustable radius
2. Add a toggle to prevent players set as friends in wurst from triggering the autopanic


Whitelisting hacks is a good idea but this is more difficult since there's no easy way to specify every single hack you want to keep on and off in wurst afaik. To make this happen I think maybe we should add a way to save the current wurst hacks state as a preset, so that state can be loaded later from a list of presets. Not only would this be a good feature in itself, but this way one could specify a preset to load when someone is in your radius, and a preset to load when someone is outside of your radius. 

Since this is a whole other feature, my plan is to first add what I'm calling "autopanic" implementing points 1 and 2 as I described in one PR. Then if there is enough interest, I (or someone else if they are interested) can implement presets in a 2nd PR. Finally, if there is interest for autopanic to have whitelisting functionality I will add that feature using presets as described in a 3rd PR. 

Let me know if this sounds like a good idea. I may have missed some features of wurst so please let me know if you think there's a better way to do this.

**Comment by Chris6ix** [comment]
@Alexander01998 You should really get rid of this annoying bot or at least make it A LOT less aggressive. This is actually a good feature suggestion and should not be closed just because there isn't somebody commenting on it every couple of days.
