### ISSUE TITLE
Very frustrating

### ISSUE THREAD

**Issue by Rolandelving** [Wurst-Imperium/Wurst7#894]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
So for a while now I’ve been using your wonderful hacked client and for some reason a while ago when I open the gui and try to scroll down, it doesn’t let me scroll down! Which means that I can’t use all of the hacks and it’s been happening ever since then. I tried downloading the latest version and it still wouldn’t let me scroll down to the other hacks please contact me back soon.
 

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. I've tried to use a more frequent version that didn't work
2. I tried finding a setting on the gui but couldn't find any setting for it
3. I tried using an odler version and still doesn't work.

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

I didn't ever crash though 

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by Alexander01998** [comment]
@Rolandelving

You've posted this same comment five times in five different places: in an email, in a YouTube comment, as a Twitter DM, on the forum, and here on GitHub. And you sent all of these within mere minutes of each other! At this point I don't even know which one of your posts I'm supposed to respond to. It's incredibly annoying to get spammed with messages like that.

I can understand that it's frustrating to be unable to scroll, but purposefully frustrating other people in revenge is not OK. To be honest, I think your mouse is broken, because the scrolling in Wurst is working fine for everyone else. From your five copy-pasted messages, it doesn't seem like you ever tested this.

Please stop messaging me!

![email](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/2209b209-50c6-49be-9743-47efda6b365f)
![YouTube](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/2824d13e-e399-466e-b5e9-066797ed9245)
![Twitter](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/bd0b559d-c82c-4618-b348-01d637c4ac87)
![WurstForum](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/0262f9a8-a3bd-4d29-aee9-38b52f6a0e96)
