### ISSUE TITLE
Suggestions for Translating Part of the Code

### ISSUE THREAD

**Issue by MineYuanlu** [Wurst-Imperium/Wurst7#896]
I think the current I18n method for setting hacks is not very reasonable and feels confusing. I think we should use the setting name and the added hacks name to determine the I18n path
For example:
```java
private final CheckboxSetting setting = new CheckboxSetting("Check line of sight", "Some english desc.", false);


public KillauraHack()
{
	super("Killaura");
	...
	addSetting(setting );
}
```
At this point, the key for I18n should be:`description.wurst.hack.killaura.check-line-of-sight`   
For the names of hacks and settings, all are converted to lowercase and spaces are converted to "-", which takes effect when adding Setting  
This is more convenient for translation management, and at the same time, only a simple export is required to obtain the default language template

I think I can do this, but I'm not sure if it's necessary? (But I really need setting translation)

**Comment by Alexander01998** [comment]
Hey @MineYuanlu!

Sorry for the confusion, but we actually already use a similar format, for example: `description.wurst.setting.killaura.check_line_of_sight`

However, currently most settings cannot be translated. This limit is on purpose, because people have been submitting huge translation pull requests (translating all 190+ strings at once) and I am finding difficult to keep up with that.

Before I could consider making every setting translatable, we would need further improvements to [TranslationHelper](https://github.com/Wurst-Imperium/TranslationHelper) or a team of volunteers willing to review incoming translation PRs.
