### ISSUE TITLE
BarrierESP Description

### ISSUE THREAD

**Issue by RealmKebab** [Wurst-Imperium/Wurst7#902]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### What type of player would find this improvement useful?

Other (please explain in description)

### Description

![image](https://github.com/Wurst-Imperium/Wurst7/assets/73048123/de7f43d1-8ada-4eed-a265-5160e88ffc36)

I know this shouldn't be labeled as an suggestion, but there's no other way to report an small mistake.
MC-47607's resolution was set to Fixed on 27th of September this year (2023)

**Comment by Alexander01998** [comment]
Hey @RealmKebab,

Indeed, [MC-47607](https://bugs.mojang.com/browse/MC-47607) was fixed in version [23w40a](https://minecraft.wiki/w/Java_Edition_23w40a), which is a snapshot for Minecraft 1.20.3. However, the bug is still present in earlier Minecraft versions like 1.20.2, which the `master` branch shown in your screenshot is currently on.

This part of the BarrierESP description is only included in versions where MC-47607 still exists. Thus, it's not an error as such but an intentional version-specific note.

For future reference, you can use the bug report template to report small mistakes - that would be the most appropriate one for such finds.

**Comment by RealmKebab** [comment]
whoops, my bad
i see now
