### ISSUE TITLE
Request Advanced Enchantments add in AutoLibrarian

### ISSUE THREAD

**Issue by D0rothy47** [Wurst-Imperium/Wurst7#973]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [ ] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack., Adding a different kind of feature.

### What type of player would find this improvement useful?

PVPers, Anarchy/faction players

### Description

Hi ! can you add more enchantment form advancedenchantments plugin in to autolibrarian hack please?

**Comment by Alexander01998** [comment]
Hey @D0rothy47!

Thanks for the suggestion. I've taken a look at the [AdvancedEnchantments plugin](https://advancedplugins.net/item/AdvancedEnchantments.1) and I see what you're after.

The thing is, this plugin creates fake enchantments by modifying the lore text of items, and in addition all of the enchantment names are customizable. This makes it difficult to identify the fake enchantments and tell them apart from regular lore text.

Because of this, adding support for the AdvancedEnchantments plugin to AutoLibrarian might not be feasible.
