### ISSUE TITLE
Chat is disabled to missing profile key

### ISSUE THREAD

**Issue by Eslorex** [Wurst-Imperium/Wurst7#974]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

When I use Wurst latest version 7.41.2 (I guess) and I get Chat is disabled to missing profile key when I try to type.

### Repro steps

Typing in the chat

### Wurst Client version

 Wurst latest version 7.41.2 

### Minecraft version

1.20.4

**Comment by Alexander01998** [comment]
Hey @Eslorex,

The "Chat disabled due to missing profile public key" message means that the server you are playing on is trying to force you to send chat messages that can be reported to Mojang (also known as "signed messages"), which is something Wurst doesn't allow by default to keep your account safe.

If you are comfortable with the risks involved, you can re-enable reportable messages by turning off the [NoChatReports](https://wurst.wiki/nochatreports) feature in Wurst. If you have the latest version, you'll find it under the "Chat" category in ClickGUI. Just toggle it off.

If you're using an older version of Wurst (before v7.35.2) or prefer to use the [Navigator GUI](https://wurst.wiki/navigator), you'll find it by opening Navigator and searching for "NoChatReports".

However, do note that by disabling NoChatReports, you run the risk of being chat-reported and potentially banned by Mojang. See [this FAQ](https://wiki.download.fo/readme/chat-reporting-faq) for more details on the risks of chat reporting.

I hope this helps! Let me know if anything is unclear.

**Comment by Eslorex** [comment]
> Hey @Eslorex,
> 
> The "Chat disabled due to missing profile public key" message means that the server you are playing on is trying to force you to send chat messages that can be reported to Mojang (also known as "signed messages"), which is something Wurst doesn't allow by default to keep your account safe.
> 
> If you are comfortable with the risks involved, you can re-enable reportable messages by turning off the [NoChatReports](https://wurst.wiki/nochatreports) feature in Wurst. If you have the latest version, you'll find it under the "Chat" category in ClickGUI. Just toggle it off.
> 
> If you're using an older version of Wurst (before v7.35.2) or prefer to use the [Navigator GUI](https://wurst.wiki/navigator), you'll find it by opening Navigator and searching for "NoChatReports".
> 
> However, do note that by disabling NoChatReports, you run the risk of being chat-reported and potentially banned by Mojang. See [this FAQ](https://wiki.download.fo/readme/chat-reporting-faq) for more details on the risks of chat reporting.
> 
> I hope this helps! Let me know if anything is unclear.

Hi again after a long time. What are the risks on this context? Would it be risky if I'm only playing with my friends? Except they don't report my account?
