### ISSUE TITLE
triggerbot sword swing animation

### ISSUE THREAD

**Issue by tadduplaysyt** [Wurst-Imperium/Wurst7#988]
### Pre-reporting checklist

- [x] I have searched existing issues and didn't find any previous reports of this bug.
- [x] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

there is sword animation due to which it can be detected like this https://www.youtube.com/watch?v=KZaQ-gN-z0g&t=20s

### Repro steps

1

### Wurst Client version

all

### Minecraft version

all

**Comment by tadduplaysyt** [comment]
pls fix this

**Comment by Alexander01998** [comment]
Hey @tadduplaysyt, thanks for the bug report!

I find that the above video doesn't really show the issue clearly, but after testing it myself I can see the animation issue you are talking about:

![A side-by-side video of TriggerBot and a manual left click being used to attack an iron golem with a wooden sword in Minecraft. The video is slowed down to show the difference in the swing animation.](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/461f9c1d-c41f-4286-8ea6-841b76ffdaa5)

Happy to confirm that this bug will be fixed in Wurst 7.42.

**Comment by tadduplaysyt** [comment]
thx
