### ISSUE TITLE
MiningBot feature

### ISSUE THREAD

**Issue by mdenials** [Wurst-Imperium/Wurst7#998]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [x] This feature doesn't already exist in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a different kind of feature., Changing the settings of existing features.

### What type of player would find this improvement useful?

Miners

### Description

Expanding the capabilities of TreeBot for mining different blocks.

**Comment by Alexander01998** [comment]
Hey @mdenials,

It's really interesting to see how TreeBot could be turned into a mining bot with these changes. It reminds me of that time when someone turned Excavator into a mining bot (#85). It's also quite funny that it now thinks ores are logs, stone is leaves, and ore veins have a tree stump.

However, I want to be clear that I wouldn't release these kinds of adaptations of other hacks as an official MiningBot feature.

TreeBot's code has a lot of issues (I know because I wrote that code). I wouldn't want to have another copy of all those issues in the codebase, as it would make it much harder to maintain. Basically every issue with that code would have to be fixed twice, once for TreeBot and once for MiningBot.

It would be great to have this as an unofficial plugin for Wurst though. Let's think about how we can put together a simple plugin system, kind of like the one suggested in #337, and then your MiningBot could be the first plugin!
